# Azure EntraID (OIDC) Configuration

# Client ID from Azure App Registration
entra.client.id=${ENTRA_ID_CLIENT_ID:}
# Client Secret
entra.client.secret=${ENTRA_ID_CLIENT_SECRET:}
# Tenant ID
entra.tenant.id=${ENTRA_ID_TENANT_ID:}
# Redirect URI
entra.redirect.uri=${ENTRA_ID_REDIRECT_URI:http://localhost:8080/smvc/login/oauth2/code/entra}