## Active Directory / LDAP settings
# AD domain (e.g., example.local or hdc.webhop.net)
ad.domain=hdc.webhop.net
# LDAP or LDAPS URL. Use ldaps://...:636/ when using TLS
ad.url=ldap://hdc.webhop.net/
